# Generated by Django 3.2.16 on 2023-01-08 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0002_alter_sharerequest_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerequest',
            name='GUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
