# Generated by Django 3.2.16 on 2023-01-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0003_alter_sharerequest_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerequest',
            name='requesting_user',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='sharerequest',
            name='share_target_user',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='shares',
            name='by_user',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='shares',
            name='for_user',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='shares',
            name='original_url',
            field=models.URLField(editable=False, max_length=5000),
        ),
    ]
