# Generated by Django 3.2.16 on 2023-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0004_auto_20230108_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerequest',
            name='target_accepted_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sharerequest',
            name='target_rejected_at',
            field=models.BigIntegerField(null=True),
        ),
    ]
